name: Build and Deploy Site
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          sudo apt-get install -y python3-markdown

      - name: Build
        run: |
          set -x
          mkdir Release
          cd Release
          cmake .. -DBINLOG_SOURCE_BROWSER_URL=https://github.com/erenon/binlog/tree/main/include/
          make Documentation
          mkdir doc
          cp ../doc/index.html *.html doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: Release/doc
          clean: true # Automatically remove deleted files from the deploy branch
